### ISSUE TITLE
Problems behind an enterprise proxy

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#107]
Some users encounter an issue behind a proxy withj the desktop app.
Execution context : Windows, Stoplight 3.5.5.

When launching Stoplight desktop app, there is an error on the hosts configuration screen. Impossible to go further. (It works fine on the same computer with a browser)
![image](https://user-images.githubusercontent.com/29988779/34004605-a22ee9aa-e0f8-11e7-9058-a6d928b55479.png)

There is also a stacktrace in the console :

> Using bypassList <local>
loading stoplight from https://next.stoplight.io
Checking for update
load stoplight error { Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\tunnel-agent\index.js:166:19)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20) code: 'ECONNRESET' }
Error: Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at CancellationToken.createPromise (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\builder-util-runtime\src\CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\builder-util-runtime\src\httpExecutor.ts:79:30)
    at ElectronHttpExecutor.request (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\builder-util-runtime\src\httpExecutor.ts:71:17)
    at GitHubProvider.httpRequest (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\src\Provider.ts:26:26)
    at C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\src\GitHubProvider.ts:34:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\out\GitHubProvider.js:108:11)
    at C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\src\AppUpdater.ts:251:37
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\out\AppUpdater.js:326:11)
    at C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\src\AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\out\AppUpdater.js:280:11)
    at NsisUpdater.checkForUpdates (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\node_modules\electron-updater\src\AppUpdater.ts:177:35)
    at checkForUpdates (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\main.js:282:15)
    at Object.<anonymous> (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\main.js:286:3)
    at Object.<anonymous> (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\app\main.js:375:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\electron.asar\browser\init.js:171:8)
    at Object.<anonymous> (C:\Users\xxxxxx\AppData\Local\Programs\stoplight-next\resources\electron.asar\browser\init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)

**Comment by marbemac** [comment]
Is this new in desktop 3.5.5, or was this happening before for these users?

**Comment by ntiss** [comment]
Probably not, because the user had the problem with 3.5.1. Upgrading in 3.5.4 and 3.5.5 didn't resolve the problem.
I didn't managed to reproduce on my 2 computers (1 Linux and 1 Windows)

**Comment by samuel-colin** [comment]
I have this problem with differents versions : 3.5.1, 3.5.4 and 3.5.5

**Comment by ntiss** [comment]
Problem resolved : the proxy hostname had changed, leading to the 503 error.
Sorry for this wrong issue.

**Comment by marbemac** [comment]
Ah ok, thanks for the follow up! I wonder if we can expose more information on error in the future - will take a quick look.
