### ISSUE TITLE
Example generation doesn't work anymore

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#97]
In modeling, when clicking on the "Generate example from schema" button, there is an error popup and this trace in the console :

ERROR generating schema. TypeError: Cannot create property 'id' on boolean 'false'
    at t (https://next.stoplight.io/static/js/vendor.61b7331.js:1:379806)
    at ue (https://next.stoplight.io/static/js/vendor.61b7331.js:1:646810)
    at ve (https://next.stoplight.io/static/js/client.61b7331.js:1:3829084)
    at Object.onClick (https://next.stoplight.io/static/js/client.61b7331.js:1:3066422)
    at n (https://next.stoplight.io/static/js/vendor.61b7331.js:1:685448)
    at r (https://next.stoplight.io/static/js/vendor.61b7331.js:1:696929)
    at n (https://next.stoplight.io/static/js/vendor.61b7331.js:1:685482)
    at https://next.stoplight.io/static/js/vendor.61b7331.js:1:744006
    at r.handleClick (https://next.stoplight.io/static/js/client.61b7331.js:1:2185400)
    at Object.l (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1030544)
    at Object.invokeGuardedCallback (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1094858)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1094975)
    at h (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1031469)
    at y (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1031937)
    at _ (https://next.stoplight.io/static/js/vendor.61b7331.js:1:1032094)
    at Array.forEach (native)

(fails with all swaggers, including the Stoplight Todo API)

**Comment by marbemac** [comment]
@casserni let's fix this up today please, after the ref builder thing (or if ref builder will take longer than a few hours, then pause and hop on this).

**Comment by casserni** [comment]
I am also having trouble replicating this error? Would you be able to provide some screen shots, or steps that you followed?

**Comment by ntiss** [comment]
Here it is :
![issue_generatefromschema](https://user-images.githubusercontent.com/29988779/33628843-4a192f0c-da02-11e7-963b-5e4d151f3b7c.gif)

**Comment by marbemac** [comment]
Deployed last night.
